### PR TITLE
Grp sum fun

### PR DESCRIPTION
**Pull request by aidandmorrison**
yo yo, here's my new function!  Need to figure out the modifier stuff still. but progress I hope!

### CODE REVIEW

**Comment by rosseji** [comment]
The objects that the your assign to in each if statement wont be returned...

ie `df_IL_hr_item`,  `df_IL_hlfhr_item`, etc will just be assigned in the environment inside the function but will never make it out in to the sunshine...

If you wrap each object in `return()`  they will exit the function. Note the `return()` cause the function to exit with that object as the result. ie it wont run past that line if the if statement its conditional on is `TRUE`.

Your code:

```
  if(interval == "hour") {
  df_IL_time %>%
    group_by(hr, Item.Name) %>%
    summarise(sales_hr = ...) -> df_IL_hr_item
  }
  
  if(interval == "30mins") {
    df_IL_time %>%
      group_by(hlfhr, Item.Name) %>%
      summarise(sales_hlfhr = ...) -> df_IL_hlfhr_item
  }
  
```

Alt 1:

```
  if(interval == "hour") {
  return(df_IL_time %>%
    group_by(hr, Item.Name) %>%
    summarise(sales_hr = ...) -> df_IL_hr_item)
  }
  
```

Alt 2:

```
  if(interval == "hour") {
  df_IL_time %>%
    group_by(hr, Item.Name) %>%
    summarise(sales_hr = ...) -> df_IL_hr_item
 return(df_IL_hr_item)
  }
  
```

**Comment by aidandmorrison** [comment]
I like the changes you made there though in those suggestions..  I understand the difference between the item being returned to the outside envirnoment, as opposed to only the internal environment of the function... But I assume that I should make sure I can get git working on my Rstudio on my desktop here, and put them in myself!

**Comment by rosseji** [comment]
I haven't made any committed changes... just thought I'd recommend some changes so that you can choose how you want to build your function.

But yeah, try and use your function:

```
output <- item_time_agg(df_IL, df_OL, interval = "hour", category = FALSE, trim = TRUE )
```

and see what happens

**Comment by rosseji** [comment]
One note: If you want to work on your function with the new functions in your evnrioment, you can make a pull request from the `master` branch to your branch (without any need for me to review) so that you get teh most up to date changes... see image below:

screen shot 2017-06-08 at 10 50 32 pm

**Comment by rosseji** [comment]
Currently your branch is 10 commits behind.

**Comment by rosseji** [comment]
The three return options are:

1.
```
 if(interval == "hour") {
  df_IL_time %>%
    group_by(hr, Item.Name) %>%
    summarise(sales_hr = ...) -> df_IL_hr_item
 return(df_IL_hr_item)
  }
```
2.
```
 if(interval == "hour") {
  df_IL_time %>%
    group_by(hr, Item.Name) %>%
    summarise(sales_hr = ...) -> df_IL_hr_item
    df_IL_hr_item
  }
```
3.
```
 if(interval == "hour") {
  df_IL_time %>%
    group_by(hr, Item.Name) %>%
    summarise(sales_hr = ...) 

  }
```

**Comment by rosseji** [comment]
was inspired after I wrote this function for working with hilda:
```
get_index_set_ <- function(set, code = F,  name = F,
                           path = "C:/Users/User/Dropbox (YSI)/YSI Team Folder/Content/R/HILDA Index/xwave index.csv") {
  
  if (code) {
    get_index_xwave() %>% filter(Set == set) %$% Code
  } else if (name) {
    get_index_xwave() %>% filter(Set == set) %$% Name
  } else {
    get_index_xwave() %>% filter(Set == set)
  }
}

```

**Pull request closed without merging**
